<?php

namespace App\Http\Resources;

use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-04-02 11:08:18
 * zip name 20220402110805_awFC5SdEW1u.zip
 */

class OtpResources extends JsonResource
{
    /**
     *    new OtpResources(object)
     *    OtpResources::collection([])
     */
    public function toArray($request)
    {
        return [
            'id_employee' => $this->id_employee,
            'kode' => $this->kode,
            'expired_in' => $this->expired_in,
            'flag_active' => $this->flag_active,
            //'updated_at' => Carbon::parse($this->updated_at)->format('Y-m-d H:i:s'),
            //'created_at' => Carbon::parse($this->created_at)->format('Y-m-d H:i:s'),
            'id' => $this->id,
        ];
    }
}
